server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    addresses: amqps://**********:*******-TwYhyrmf8zUM05tZ9bjL@jackal.rmq.cloudamqp.com/******

broker:
  queue:
    message:
      name: default_message
